sudo: false
language: go
go:
- 1.x

env:
  - GO111MODULE=on

install:
  - go get -v -d github.com/carpenterscode/superscriber

script:
  - go get github.com/golang/mock/gomock
  - go install github.com/golang/mock/mockgen
  - go generate ./...
  - go test
